"""empty message

Revision ID: 42f5b42e2d90
Revises: 0661bee0bc99
Create Date: 2018-02-02 06:00:29.227244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42f5b42e2d90'
down_revision = '0661bee0bc99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('login_code', sa.String(length=1), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'login_code')
    # ### end Alembic commands ###
