"""empty message

Revision ID: 6b983d01403f
Revises: 3d32932b1de5
Create Date: 2018-02-20 15:33:46.176107

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6b983d01403f'
down_revision = '3d32932b1de5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('login_static', sa.String(length=1), nullable=True))
    op.drop_column('users', 'login_code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('login_code', mysql.VARCHAR(length=1), nullable=True))
    op.drop_column('users', 'login_static')
    # ### end Alembic commands ###
