"""empty message

Revision ID: 9f2196ffec9a
Revises: 6b983d01403f
Create Date: 2018-02-21 23:08:40.427945

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9f2196ffec9a'
down_revision = '6b983d01403f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('config')
    op.add_column('site_config', sa.Column('name', sa.String(length=124), nullable=True))
    op.create_index(op.f('ix_site_config_name'), 'site_config', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_site_config_name'), table_name='site_config')
    op.drop_column('site_config', 'name')
    op.create_table('config',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('webname', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('shop_url', mysql.VARCHAR(length=124), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
